### ISSUE TITLE
如何设置弹窗显示位置呢

### ISSUE THREAD

**Issue by jp1017** [Lans/multiple_dialog#1]
比如，距离屏幕右侧20，顶部100，再比如占屏幕1/3显示弹窗等等

**Comment by Lans** [comment]
你可以看下新的CustomDialog ，参数gravity 从上到下可以调整位置（ -1 到 0 ）为上到中间 （0 到 1）位下面位置，基本Dialog都是居中的，所以没有留设置左右距离的
